services:
  postgres:
    image: cgr.dev/chainguard/postgres
    container_name: pg17-local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/conf/pg_hba.prod.conf:/etc/postgresql/pg_hba.conf:ro
      - ./server/conf/postgresql.prod.conf:/etc/postgresql/postgresql.conf:ro
      - ./server/certs:/certs:ro
    command:
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/certs/server.crt"
      - "-c"
      - "ssl_key_file=/certs/server.key"
      - "-c"
      - "ssl_ca_file=/certs/ca.crt"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  go-server:
    container_name: go-server
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data:rw
      - ./backup:/app/backup:rw
      - ./certs:/certs:ro
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:postgres@pg17-local:5432/mydb?sslmode=verify-full&sslcert=/app/certs/client.crt&sslkey=/app/certs/client.key&sslrootcert=/app/certs/ca.crt
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["./server/go-server"]

  web:
    container_name: web-ui
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Nginx in Dockerfile serves on 80, mapped to 3000 locally
    depends_on:
      - go-server
    restart: unless-stopped

volumes:
  pg_data:
