package main

import (
	"encoding/csv"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
)

// Scholarships students apply for themselves (DAAD, Chevening, Erasmus Mundus, ...), curated in
// backup/scholarships.csv and served by destination country and the student's nationality.
// Eligibility rules and deadlines change every year, so entries link to the official page.
//
// Columns: id,name,provider,destination_countries,levels,eligible_nationalities,covers,
// application_window,official_url,verified,notes
//
//	destination_countries: ISO alpha-2 codes ';'-separated, "EU" for any EU member state, "*" for any
//	eligible_nationalities: ISO codes, "*" for (nearly) all, "developing" for developing countries,
//	                        "!XX" to exclude a country, "!EEA" to exclude EU/EEA nationals
//
// A programme whose application_window is "discontinued" is kept for the record but not served.
//
// Feeds generated by server/scripts/scholarships/*.py (data/scholarships/*.csv, same columns) are
// served after the curated list; a feed row whose name matches a curated programme is dropped.
const scholarshipsFile = "scholarships.csv"
const scholarshipFeedsDir = "scholarships"

var euMembers = map[string]bool{
	"AT": true, "BE": true, "BG": true, "HR": true, "CY": true, "CZ": true, "DK": true, "EE": true,
	"FI": true, "FR": true, "DE": true, "GR": true, "HU": true, "IE": true, "IT": true, "LV": true,
	"LT": true, "LU": true, "MT": true, "NL": true, "PL": true, "PT": true, "RO": true, "SK": true,
	"SI": true, "ES": true, "SE": true,
}

// EEA = EU members plus Iceland, Liechtenstein and Norway.
func inEEA(country string) bool {
	return euMembers[country] || country == "IS" || country == "LI" || country == "NO"
}

type scholarship struct {
	ID                    string   `json:"id"`
	Name                  string   `json:"name"`
	Provider              string   `json:"provider"`
	Destinations          []string `json:"destinations"`
	Levels                []string `json:"levels"`
	EligibleNationalities []string `json:"eligible_nationalities"`
	Covers                string   `json:"covers"`
	ApplicationWindow     string   `json:"application_window"`
	URL                   string   `json:"url"`
	Verified              bool     `json:"verified"`
	Notes                 string   `json:"notes"`
	Source                string   `json:"source"` // "curated", or the feed's name ("daad")
	// "eligible", "check" (no nationality given, or a rule like "developing countries"), set per request
	Eligibility string `json:"eligibility,omitempty"`
}

var scholarshipCache struct {
	sync.Mutex
	stamp string
	items []scholarship
}

func splitCodes(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ";") {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, strings.ToUpper(p))
		}
	}
	return out
}

func loadScholarships() ([]scholarship, error) {
	paths := []string{filepath.Join(getRootDirPath(BACKUP_DIR), scholarshipsFile)}
	feeds, _ := filepath.Glob(filepath.Join(getRootDirPath(DATA_DIR), scholarshipFeedsDir, "*.csv"))
	sort.Strings(feeds)
	paths = append(paths, feeds...)

	// The cache is valid while no file was added, removed or changed.
	var stamp strings.Builder
	for _, p := range paths {
		if info, err := os.Stat(p); err == nil {
			stamp.WriteString(p + "@" + info.ModTime().String() + ";")
		}
	}
	scholarshipCache.Lock()
	defer scholarshipCache.Unlock()
	if stamp.String() == scholarshipCache.stamp {
		return scholarshipCache.items, nil
	}

	var items []scholarship
	curated := map[string]bool{}
	for i, p := range paths {
		source := "curated"
		if i > 0 {
			source = strings.TrimSuffix(filepath.Base(p), ".csv")
		}
		rows, err := readScholarshipFile(p, source)
		if err != nil {
			if i == 0 && os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		for _, sc := range rows {
			key := scholarshipNameKey(sc.Name)
			if source == "curated" {
				curated[key] = true
			} else if curated[key] {
				continue
			}
			items = append(items, sc)
		}
	}
	scholarshipCache.stamp, scholarshipCache.items = stamp.String(), items
	return items, nil
}

// scholarshipNameKey compares programme names across sources, ignoring a "DAAD " or "Research Grants - "
// prefix and parenthesised text: "DAAD Helmut-Schmidt-Programme (Public Policy and Good Governance)" =
// "Helmut-Schmidt-Programme"; "DAAD Doctoral Programmes in Germany" = "Research Grants - Doctoral
// Programmes in Germany".
var parenthesised = regexp.MustCompile(`\([^)]*\)`)

func scholarshipNameKey(name string) string {
	name = parenthesised.ReplaceAllString(strings.TrimSpace(name), "")
	name = strings.TrimPrefix(strings.TrimPrefix(name, "DAAD "), "Research Grants - ")
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func readScholarshipFile(path, source string) ([]scholarship, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	records, err := csv.NewReader(f).ReadAll()
	if err != nil {
		return nil, err
	}
	var items []scholarship
	for i, r := range records {
		if i == 0 || len(r) < 11 {
			continue
		}
		items = append(items, scholarship{
			ID: r[0], Name: r[1], Provider: r[2],
			Destinations:          splitCodes(r[3]),
			Levels:                strings.Split(strings.ToLower(r[4]), ";"),
			EligibleNationalities: splitCodes(r[5]),
			Covers:                r[6], ApplicationWindow: r[7], URL: r[8],
			Verified: strings.EqualFold(strings.TrimSpace(r[9]), "yes"),
			Notes:    r[10],
			Source:   source,
		})
	}
	return items, nil
}

func (s scholarship) goesTo(country string) bool {
	for _, d := range s.Destinations {
		if d == "*" || d == country || (d == "EU" && euMembers[country]) {
			return true
		}
	}
	return false
}

// eligibilityFor returns "eligible", "check" or "" (not eligible).
func (s scholarship) eligibilityFor(nationality string) string {
	if nationality == "" {
		return "check"
	}
	result := ""
	for _, n := range s.EligibleNationalities {
		switch {
		case n == "!"+nationality, n == "!EEA" && inEEA(nationality):
			return ""
		case n == "!EEA":
			result = "eligible" // open to everyone outside the EEA
		case n == nationality || n == "*":
			result = "eligible"
		case n == "DEVELOPING" && result == "":
			result = "check"
		}
	}
	return result
}

// getExplorerScholarships: GET /explorer/scholarships?country=DE&nationality=PK&level=phd
func getExplorerScholarships(w http.ResponseWriter, r *http.Request) {
	items, err := loadScholarships()
	if err != nil {
		writeError(w, r, http.StatusInternalServerError, "failed to load scholarships", err)
		return
	}
	country := strings.ToUpper(strings.TrimSpace(r.URL.Query().Get("country")))
	nationality := strings.ToUpper(strings.TrimSpace(r.URL.Query().Get("nationality")))
	level := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("level")))

	out := []scholarship{}
	for _, s := range items {
		if strings.EqualFold(strings.TrimSpace(s.ApplicationWindow), "discontinued") {
			continue
		}
		if country != "" && !s.goesTo(country) {
			continue
		}
		if level != "" && !strings.Contains(";"+strings.Join(s.Levels, ";")+";", ";"+level+";") {
			continue
		}
		e := s.eligibilityFor(nationality)
		if e == "" {
			continue
		}
		s.Eligibility = e
		out = append(out, s)
	}
	// Programmes for this country first, then regional (EU), then open-destination ones (HEC, ...).
	sort.SliceStable(out, func(i, j int) bool { return destinationRank(out[i], country) < destinationRank(out[j], country) })
	writeJSON(w, http.StatusOK, out)
}

// destinationRank: 0 when the programme names this country, 1 for a region (EU), 2 for anywhere.
func destinationRank(s scholarship, country string) int {
	rank := 2
	for _, d := range s.Destinations {
		switch {
		case d == country:
			return 0
		case d == "EU":
			rank = 1
		}
	}
	return rank
}
