package main

import (
	"regexp"
	"strings"
)

var TOP_UNIVERSITIES_AGAINST_COUNTRY = map[string][]string{
	"USA": {
		"Massachusetts Institute of Technology",
		"Carnegie Mellon University",
		"Stanford University",
		"University of California--Berkeley",
		"University of Illinois--Urbana-Champaign",
		"Georgia Institute of Technology",
		"Cornell University",
		"Princeton University",
		"University of Texas--Austin",
		"University of Washington",
		"University of Michigan--Ann Arbor",
		"California Institute of Technology",
		"Columbia University",
		"University of California--San Diego",
		"University of Wisconsin--Madison",
		"University of California--Los Angeles",
		"University of Maryland--College Park",
		"University of Pennsylvania",
		"Harvard University",
		"Purdue University--West Lafayette",
		"Johns Hopkins University",
		"University of Massachusetts--Amherst",
		"University of Southern California",
		"Yale University",
		"Duke University",
		"Rice University",
		"Brown University",
		"New York University",
		"Northeastern University",
		"Northwestern University",
		"University of California--Irvine",
		"University of California--Santa Barbara",
		"University of Chicago",
		"University of North Carolina--Chapel Hill",
		"Ohio State University",
		"University of Minnesota--Twin Cities",
		"University of Virginia",
		"Virginia Tech",
		"Arizona State University",
		"Pennsylvania State University--University Park",
		"Texas A&M University--College Station",
		"University of California--Davis",
		"University of Colorado--Boulder",
		"Rutgers University--New Brunswick",
		"Boston University",
		"Dartmouth College",
		"Stony Brook University--SUNY",
		"University of Florida",
		"Vanderbilt University",
		"Washington University in St. Louis",
		"Indiana University--Bloomington",
		"North Carolina State University",
		"University of Pittsburgh",
		"Michigan State University",
		"University of California--Riverside",
		"University of California--Santa Cruz",
		"University of Illinois Chicago",
		"University of Notre Dame",
		"University of Rochester",
		"University of Utah",
		"Tufts University",
		"University of Arizona",
		"University of Texas--Dallas",
		"George Mason University",
		"Iowa State University",
		"Oregon State University",
		"Rensselaer Polytechnic Institute",
		"Syracuse University",
		"University at Buffalo--SUNY",
		"University of Central Florida",
		"Case Western Reserve University",
		"Georgetown University",
		"George Washington University",
		"Rochester Institute of Technology",
		"Toyota Technological Institute at Chicago",
		"University of Delaware",
		"University of Iowa",
		"University of Oregon",
		"William & Mary",
		"Clemson University",
		"Emory University",
		"New Jersey Institute of Technology",
		"Stevens Institute of Technology",
		"University of Georgia",
		"University of Maryland, Baltimore County",
		"University of Nebraska--Lincoln",
		"University of Tennessee--Knoxville",
		"Auburn University",
		"Colorado School of Mines",
		"Drexel University",
		"Florida State University",
		"University of Connecticut",
		"University of Kansas",
		"Binghamton University--SUNY",
		"Colorado State University",
		"Illinois Institute of Technology",
		"Lehigh University",
		"University of North Carolina--Charlotte",
		"University of South Florida",
		"University of Texas--Arlington",
		"Washington State University",
		"Worcester Polytechnic Institute",
		"Brandeis University",
		"Kansas State University",
		"Naval Postgraduate School",
		"Temple University",
		"University of California--Merced",
		"University of Kentucky",
		"University of New Mexico",
		"Brigham Young University",
	},
	"CAN": {
		"University of Toronto",
		"University of British Columbia",
		"McGill University",
		"University of Waterloo",
		"University of Alberta",
		"University of Montreal",
		"Simon Fraser University",
		"McMaster University",
		"University of Calgary",
		"Queen's University",
		"Western University",
		"University of Ottawa",
		"Dalhousie University",
		"Carleton University",
		"Concordia University",
		"York University",
		"University of Victoria",
		"Université Laval",
		"University of Saskatchewan",
		"University of Manitoba",
	},
	"MEX": {
		"National Autonomous University of Mexico",
		"Monterrey Institute of Technology",
		"National Polytechnic Institute",
		"Universidad Autónoma Metropolitana",
		"Universidad de Guadalajara",
		"Universidad Autónoma de Nuevo León",
		"Centro de Investigación y de Estudios Avanzados",
		"Universidad de las Américas Puebla",
		"Instituto Politécnico Nacional",
		"Universidad Iberoamericana",
	},
	"GBR": {
		"University of Oxford",
		"University of Cambridge",
		"Imperial College London",
		"University College London",
		"University of Edinburgh",
		"King's College London",
		"London School of Economics",
		"University of Manchester",
		"University of Bristol",
		"University of Warwick",
		"University of Glasgow",
		"University of Southampton",
		"University of Birmingham",
		"University of Leeds",
		"Durham University",
		"University of Sheffield",
		"University of Nottingham",
		"Queen Mary University of London",
		"Lancaster University",
		"University of York",
		"University of Exeter",
		"Newcastle University",
		"University of Liverpool",
		"University of Sussex",
		"Cardiff University",
	},
	"DEU": {
		"Technical University of Munich",
		"Ludwig Maximilian University of Munich",
		"Heidelberg University",
		"Humboldt University of Berlin",
		"Free University of Berlin",
		"RWTH Aachen University",
		"Technical University of Berlin",
		"University of Freiburg",
		"University of Göttingen",
		"University of Bonn",
		"University of Tübingen",
		"Karlsruhe Institute of Technology",
		"University of Hamburg",
		"University of Mannheim",
		"University of Stuttgart",
		"Technical University of Darmstadt",
		"University of Cologne",
		"University of Erlangen-Nuremberg",
		"University of Frankfurt",
		"Dresden University of Technology",
	},
	"FRA": {
		"Sorbonne University",
		"École Polytechnique",
		"École Normale Supérieure",
		"University of Paris-Saclay",
		"PSL Research University",
		"Université Paris Cité",
		"Grenoble Alpes University",
		"CentraleSupélec",
		"Télécom Paris",
		"Institut Polytechnique de Paris",
		"École des Ponts ParisTech",
		"University of Strasbourg",
		"Aix-Marseille University",
		"University of Bordeaux",
		"University of Lyon",
		"University of Toulouse",
		"University of Lille",
		"INSA Lyon",
		"École Centrale de Lyon",
		"IMT Atlantique",
	},
	"ITA": {
		"Sapienza University of Rome",
		"University of Bologna",
		"University of Milan",
		"Polytechnic University of Milan",
		"University of Padua",
		"University of Turin",
		"University of Florence",
		"University of Pisa",
		"Polytechnic University of Turin",
		"University of Naples Federico II",
		"University of Rome Tor Vergata",
		"University of Trento",
		"University of Genoa",
		"Scuola Normale Superiore di Pisa",
		"Sant'Anna School of Advanced Studies",
	},
	"ESP": {
		"University of Barcelona",
		"Autonomous University of Barcelona",
		"Complutense University of Madrid",
		"Autonomous University of Madrid",
		"Polytechnic University of Catalonia",
		"Pompeu Fabra University",
		"University of Valencia",
		"Carlos III University of Madrid",
		"Polytechnic University of Madrid",
		"University of Granada",
		"University of Seville",
		"University of the Basque Country",
		"University of Zaragoza",
		"University of Santiago de Compostela",
		"IE University",
	},
	"NLD": {
		"University of Amsterdam",
		"Delft University of Technology",
		"Utrecht University",
		"Leiden University",
		"Eindhoven University of Technology",
		"University of Groningen",
		"Erasmus University Rotterdam",
		"Wageningen University",
		"Radboud University",
		"Maastricht University",
		"VU Amsterdam",
		"University of Twente",
		"Tilburg University",
	},
	"CHE": {
		"ETH Zurich",
		"École Polytechnique Fédérale de Lausanne",
		"University of Zurich",
		"University of Geneva",
		"University of Bern",
		"University of Basel",
		"University of Lausanne",
		"University of St. Gallen",
		"University of Fribourg",
		"Università della Svizzera italiana",
	},
	"SWE": {
		"Lund University",
		"KTH Royal Institute of Technology",
		"Uppsala University",
		"Stockholm University",
		"University of Gothenburg",
		"Chalmers University of Technology",
		"Karolinska Institute",
		"Linköping University",
		"Umeå University",
		"Swedish University of Agricultural Sciences",
	},
	"NOR": {
		"University of Oslo",
		"Norwegian University of Science and Technology",
		"University of Bergen",
		"University of Tromsø",
		"Norwegian School of Economics",
		"BI Norwegian Business School",
		"University of Stavanger",
		"University of Agder",
		"Oslo Metropolitan University",
	},
	"DNK": {
		"University of Copenhagen",
		"Technical University of Denmark",
		"Aarhus University",
		"University of Southern Denmark",
		"Aalborg University",
		"Copenhagen Business School",
		"Roskilde University",
		"IT University of Copenhagen",
	},
	"POL": {
		"University of Warsaw",
		"Jagiellonian University",
		"Warsaw University of Technology",
		"AGH University of Science and Technology",
		"Adam Mickiewicz University",
		"University of Wrocław",
		"Gdańsk University of Technology",
		"Poznań University of Technology",
		"Silesian University of Technology",
		"Nicolaus Copernicus University",
	},
	"CHN": {
		"Tsinghua University",
		"Peking University",
		"Fudan University",
		"Shanghai Jiao Tong University",
		"Zhejiang University",
		"University of Science and Technology of China",
		"Nanjing University",
		"Wuhan University",
		"Harbin Institute of Technology",
		"Xi'an Jiaotong University",
		"Sun Yat-sen University",
		"Beihang University",
		"Southeast University",
		"Beijing Institute of Technology",
		"Tianjin University",
		"Nankai University",
		"South China University of Technology",
		"Sichuan University",
		"Huazhong University of Science and Technology",
		"Tongji University",
	},
	"JPN": {
		"University of Tokyo",
		"Kyoto University",
		"Tokyo Institute of Technology",
		"Osaka University",
		"Tohoku University",
		"Nagoya University",
		"Kyushu University",
		"Hokkaido University",
		"Keio University",
		"Waseda University",
		"Tokyo University of Science",
		"Tsukuba University",
		"Kobe University",
		"Hiroshima University",
		"Chiba University",
		"Tokyo Metropolitan University",
		"Yokohama National University",
		"Nara Institute of Science and Technology",
	},
	"IND": {
		"Indian Institute of Technology Bombay",
		"Indian Institute of Technology Delhi",
		"Indian Institute of Technology Madras",
		"Indian Institute of Technology Kanpur",
		"Indian Institute of Technology Kharagpur",
		"Indian Institute of Science",
		"Indian Institute of Technology Roorkee",
		"Indian Institute of Technology Guwahati",
		"Indian Institute of Technology Hyderabad",
		"Delhi University",
		"Jawaharlal Nehru University",
		"University of Mumbai",
		"Anna University",
		"University of Calcutta",
		"Jadavpur University",
		"Birla Institute of Technology and Science",
		"Vellore Institute of Technology",
		"Indian Statistical Institute",
		"International Institute of Information Technology Hyderabad",
		"Indian Institute of Technology (BHU) Varanasi",
	},
	"KOR": {
		"Seoul National University",
		"Korea Advanced Institute of Science and Technology",
		"Pohang University of Science and Technology",
		"Yonsei University",
		"Korea University",
		"Sungkyunkwan University",
		"Hanyang University",
		"Kyung Hee University",
		"Ewha Womans University",
		"Gwangju Institute of Science and Technology",
		"Ulsan National Institute of Science and Technology",
		"Sogang University",
		"Chung-Ang University",
		"Ajou University",
	},
	"SGP": {
		"National University of Singapore",
		"Nanyang Technological University",
		"Singapore Management University",
		"Singapore University of Technology and Design",
		"Singapore Institute of Technology",
	},
	"AUS": {
		"University of Melbourne",
		"Australian National University",
		"University of Sydney",
		"University of New South Wales",
		"University of Queensland",
		"Monash University",
		"University of Western Australia",
		"University of Adelaide",
		"University of Technology Sydney",
		"RMIT University",
		"Queensland University of Technology",
		"Curtin University",
		"Macquarie University",
		"University of Newcastle",
		"Deakin University",
		"University of Wollongong",
		"Griffith University",
		"La Trobe University",
	},
	"NZL": {
		"University of Auckland",
		"University of Otago",
		"University of Canterbury",
		"Victoria University of Wellington",
		"Massey University",
		"University of Waikato",
		"Lincoln University",
		"Auckland University of Technology",
	},
	"BRA": {
		"University of São Paulo",
		"State University of Campinas",
		"Federal University of Rio de Janeiro",
		"Pontifical Catholic University of Rio de Janeiro",
		"Federal University of São Paulo",
		"Federal University of Minas Gerais",
		"University of Brasília",
		"Federal University of Rio Grande do Sul",
		"State University of São Paulo",
		"Federal University of Santa Catarina",
		"Federal University of Pernambuco",
		"Federal University of Bahia",
		"Pontifical Catholic University of São Paulo",
		"Federal University of Paraná",
	},
	"ARG": {
		"University of Buenos Aires",
		"National University of Córdoba",
		"National University of La Plata",
		"National Technological University",
		"Universidad Torcuato di Tella",
		"Universidad Austral",
		"Pontifical Catholic University of Argentina",
		"National University of Rosario",
		"National University of Cuyo",
		"University of San Andrés",
	},
	"CHL": {
		"Pontifical Catholic University of Chile",
		"University of Chile",
		"Universidad de Santiago de Chile",
		"Universidad de Concepción",
		"Universidad Técnica Federico Santa María",
		"Universidad Adolfo Ibáñez",
		"Universidad de los Andes",
		"Universidad Austral de Chile",
		"Universidad de Valparaíso",
	},
	"ZAF": {
		"University of Cape Town",
		"University of the Witwatersrand",
		"Stellenbosch University",
		"University of Pretoria",
		"University of Johannesburg",
		"University of KwaZulu-Natal",
		"Rhodes University",
		"North-West University",
		"Nelson Mandela University",
		"University of the Western Cape",
	},
	"EGY": {
		"Cairo University",
		"American University in Cairo",
		"Ain Shams University",
		"Alexandria University",
		"Mansoura University",
		"Assiut University",
		"Helwan University",
		"Zagazig University",
		"Tanta University",
		"Suez Canal University",
	},
	"NGA": {
		"University of Ibadan",
		"University of Lagos",
		"Obafemi Awolowo University",
		"Ahmadu Bello University",
		"University of Nigeria",
		"University of Benin",
		"Covenant University",
		"University of Port Harcourt",
		"University of Ilorin",
		"Bayero University",
	},
	"SAU": {
		"King Abdulaziz University",
		"King Saud University",
		"King Abdullah University of Science and Technology",
		"King Fahd University of Petroleum and Minerals",
		"Alfaisal University",
		"Princess Nourah bint Abdulrahman University",
		"Imam Abdulrahman Bin Faisal University",
		"King Khalid University",
		"Taibah University",
		"Umm Al-Qura University",
	},
	"ARE": {
		"Khalifa University",
		"United Arab Emirates University",
		"American University of Sharjah",
		"University of Sharjah",
		"American University in Dubai",
		"Zayed University",
		"Ajman University",
		"Abu Dhabi University",
		"New York University Abu Dhabi",
		"Masdar Institute",
	},
}

// normalizeInstitutionName standardizes university names for better matching.
func normalizeInstitutionName(name string) string {
	name = strings.TrimSpace(name)

	// Replace connectors/punctuation with spaces but keep words intact
	re := regexp.MustCompile(`[.,;:/()']+`)
	name = re.ReplaceAllString(name, " ")

	// Add spaces around hyphens between words (e.g., "A-B" -> "A - B")
	re = regexp.MustCompile(`(\w)-(\w)`)
	name = re.ReplaceAllString(name, "$1 - $2")

	// Collapse multiple spaces
	re = regexp.MustCompile(`\s+`)
	name = re.ReplaceAllString(name, " ")

	// Trim whitespace
	name = strings.TrimSpace(name)

	// If the name starts with "Univ of ", replace it with "University Of "
	if strings.HasPrefix(strings.ToLower(name), "univ of ") {
		name = "University Of " + strings.TrimSpace(name[8:])
	}
	if strings.HasPrefix(strings.ToLower(name), "univ. of ") {
		name = "University Of " + strings.TrimSpace(name[9:])
	}
	if strings.HasPrefix(strings.ToLower(name), "univ ") {
		name = "University " + strings.TrimSpace(name[5:])
	}
	if strings.HasPrefix(strings.ToLower(name), "univ. ") {
		name = "University " + strings.TrimSpace(name[6:])
	}
	if strings.HasPrefix(strings.ToLower(name), "texas a and m") {
		// Special case for Texas A&M (case-insensitive)
		// Preserve any trailing text after "Texas A And M"
		name = "Texas A&M"
		if len(name) > len("Texas A And M") {
			suffix := strings.TrimSpace(name[len("Texas A And M"):])
			if suffix != "" {
				name += " " + suffix
			}
		}
	}

	return name
}
