import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The notebook holds living articles — pieces that get revised rather than
 * dated. One category per project under ~/code/open-concept-lab/ai/.
 */
const sidebars: SidebarsConfig = {
  notebookSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
